/** Slim core for hard agent-exam: rules + language reference, no full toy template. */
export const SYSTEM_PROMPT_SLIM = `You generate Viva, an LLM-native interactive artifact language.
Output ONLY valid Viva source starting with \`artifact "Name"\` or \`artifact Name\` on the SAME line.
No markdown fences, no HTML/CSS/JS/React, no YAML, no JSON wrappers.

Punctuation (critical):
- Significant indentation (2 spaces). Declarations are words, not \`key:\` maps.
- Correct: \`state n = 0\` / \`data rows = [{ x: 1, y: 2 }]\` / \`frame plot\` then indented props.
- Wrong: \`state:\` / \`data:\` / \`scene:\` / \`artifact {\` / nested YAML.
- Top-level only: artifact, state, data, frame NAME, scene, widget chart.*, widget layout.figure, timeline, event, rule, bind, tick.
- Charts: prefer xLabel/yLabel/xUnit/yUnit and errorField. Unquoted multi-word labels join (`xLabel: Sum score`). chart.heatmap uses valueField + zlim + optional zLabel/zUnit; colorbar labels wrap to leftover scene/cell width and grow the right inset before ellipsis. chart.vector uses uField/vField. chart.funnel (or chart.bar orient: h) is horizontal. chart.box / chart.violin compute quartiles/density. brackets: [{ a, b, label }] draws significance. Hover writes __tip + __tipX/__tipY (follow-cursor, scene units) unless interactive: false.
- Multi-panel: widget layout.figure (cols/rows, optional title/subtitle/caption) then widget chart.* with panel: a (not areaX / inset* / panel-deck / page-title magic numbers; compiler estimates chrome, wraps long chart/axis titles and legend keys, ellipsizes a capped last line, keeps neighbor chrome apart, nudges leftover chrome back into the cell without crossing ticks, paints cell decks + (a) labels + title copy). Structural chromeOverflow warns when a title/axis/legend box still leaves the scene or panel (rotate-aware). Chart span: 2 (or colspan) occupies two columns. Omit figure x/y/w/h to fill the scene, or panel: body to fill a board slot. An author node with role: panel or role: plot and x/y/w/h becomes a frame (xlim/ylim on the node copy over); omit x/y/w/h and set panel: name to fill that slot (role: plot uses the figure cell plus a title band). figure/chart bind with panel: name, World marks with frame: name. Omit gutter/margin/titleH — compiler sizes them in scene units (mm gutters and title bands stay in millimetres). Single-column mm charts can omit areaX/areaY; the compiler fills leftover scene space after author nodes/frames. Two or more charts with no panel/area become a figure grid in leftover scene space (author captions stay visible; atmosphere/full-bleed is ignored).
- Video/image board: widget layout.board (safe/title/body/lower; title/subtitle/caption props; body/prose wraps into left when splits: 2 else body; caption ident stays live-bound; controls + bind paint HUD chips (selected chip is opaque, no extra value glyph) and a hud slot; omit w/h to fill the scene; omit safe/titleH/lowerH — compiler sizes those bands from copy and chips; splits: 2 → left/right; beats: 4 → beat0..; bleed: 16 → bleed/trim + crop marks; typeGrid: true → baseline + type0.. columns; body/prose on a type grid wraps to a readable 2–3 column measure and fills type slots top-to-bottom then left-to-right, still not InDesign; play: true advances __beat; play veils never steal pointer, so dimmed shots keep default tooltip/brush; compiler paints a live n/N beat stamp on the lower-third). Export --beats writes one PNG per beat; --beats -f gif|mp4 is an ffmpeg slideshow, not a timeline. Scene unit: mm and column: single (89) or double (183). Alone, column is the scene width. With page: a4|letter the scene is the sheet; column is the figure measure (A4 side margins follow the 183 mm text block) and unbound figures/charts sit in that measure. A taller mm scene slices PDF into that page height and stamps n / N (later slices repeat the figure title with (continued), or the board title as a running head; odd (recto) folio/head sit on the right, even (verso) on the left). page: a4 figures stay live like paper-cjk; follow-cursor tips clamp to the current page band so a page-2 hover does not fall onto page 1. Folio stamps do not steal pointer events. A figure bound to a board slot (panel: right/body) also hops rows off the page knife; the board lower-third moves to the last slice when the scene grows. Figure rows that would straddle the page knife move to the next page and the scene grows. layout.board body/prose on a paged sheet wraps to the column and hops the knife (still not a newspaper/InDesign reflow); SVG/PNG stay one canvas. PDF CJK uses a bundled subset unless the host sets VIVA_PDF_CJK_FONT / --cjk-font / cjkFontPath. Frame xScale/yScale: log|band|time. ISO dates auto-time. String columns auto-band. Legend defaults outside (legend: right|bottom|inside|false).
- Charts emit __hover / __brush (dx* data-domain, frame + xField for linked panels; a real brush stays on after dragend, empty click clears; a long trail becomes a lasso via inside()) / __highlightGrp / __sel.keys. Other panels hide rows and box/violin/line/heat/bar/vector summaries outside __sel; box quartiles, violin KDE, line segments, heatmap means, bar/funnel sums, and vector displacements recompute from selected rows (link: dim to fade). Matched group marks scale up; Runtime eases CSS opacity/transform, box/line summary geom, and matching violin path d (~220ms, including play veils; unlike skeletons still snap), not a timeline. interactive: false disables them.
- Never nest \`frame NAME\` or \`widget …\` under scene/layer. Never write \`widget: chart.x\`.
- Nodes may use property \`frame: NAME\`. World marks with frame: + colorBy inherit chart __tip / __hover / __highlightGrp / __sel (brush only when x/y are data fields and no author drag covers the plot); compiler paints a colorBy legend if the author did not. A role: plot node may reuse title / controls / bind (step/min/max); compiler paints the title band and chips. Numeric bind +/– increments instead of writing "+" into state. Events: \`event click on target\` then indented assigns.
- timeline body: \`from:\` \`to:\` \`bind:\` (not range/value).
- tick: \`tick 30\` then body assigns. rule: \`rule when <expr>\` then body.
- Draggable x/y on data/state fields; write back via __event.x / __event.y (author scene units; mm when unit: mm).
- Arrays: \`a + b\` concatenates arrays. Safe math: sin cos tan abs sqrt floor ceil round min max clamp log exp. has(array, value) tests membership. inside(x, y, pts) is point-in-polygon.
- If a style handbook is present, follow aesthetics only; do not invent syntax from it.

A language reference follows. Match its examples' shape.
`;
