import type { StylePreset } from "../types.js";

export const DEFAULT_HANDBOOK_ID = "print-nature";

export const printNaturePreset: StylePreset = {
  id: "print-nature",
  scene: {
    background: "#ffffff",
    fontFamily: "IBM Plex Sans, Helvetica, Arial, sans-serif",
  },
  palette: {
    /** Wong / Nature Methods colorblind-safe categorical (default). */
    categorical: [
      "#0072B2",
      "#E69F00",
      "#009E73",
      "#CC79A7",
      "#56B4E9",
      "#D55E00",
      "#F0E442",
      "#999999",
    ],
    /** Visible on white backgrounds (no near-white steps). */
    sequential: [
      "#c6dbef",
      "#9ecae1",
      "#6baed6",
      "#4292c6",
      "#2171b5",
      "#1a5a9e",
      "#084594",
    ],
    accent: "#0072B2",
    foreground: "#1a1a1a",
    muted: "#6b7280",
    background: "#ffffff",
  },
  typography: {
    title: { size: 12, weight: 600, letterSpacing: 0.35 },
    subtitle: { size: 10, weight: 500, letterSpacing: 0.15 },
    caption: { size: 8, weight: 400, letterSpacing: 0.1 },
    axis: { size: 9, weight: 500, letterSpacing: 0.2 },
    tick: { size: 8, weight: 400, letterSpacing: 0.08 },
    legend: { size: 8, weight: 500, letterSpacing: 0.1 },
    panel: { size: 11, weight: 700, letterSpacing: 0.15 },
  },
  roles: {
    scene: { fill: "#ffffff" },
    panel: { fill: "#ffffff", stroke: "#cbd5e1", strokeWidth: 1, radius: 0 },
    plot: { fill: "#ffffff", stroke: "#94a3b8", strokeWidth: 1, radius: 0 },
    "plot-border": { stroke: "#6b7280", strokeWidth: 1 },
    axis: { stroke: "#374151", strokeWidth: 1.25 },
    grid: { stroke: "#e5e7eb", strokeWidth: 1, dash: "4 4", opacity: 0.9 },
    title: { fill: "#111827", font: 12, fontWeight: 600 },
    subtitle: { fill: "#4b5563", font: 10 },
    caption: { fill: "#6b7280", font: 8 },
    legend: { stroke: "#374151", strokeWidth: 1 },
    "legend-label": { fill: "#374151", font: 8 },
    "panel-label": { fill: "#0072B2", font: 11, fontWeight: 700 },
    subpanel: { fill: "#ffffff", stroke: "#d1d5db", strokeWidth: 1, radius: 0 },
    colorbar: { stroke: "#9ca3af", strokeWidth: 1 },
    mark: { stroke: "#1f2937", strokeWidth: 1, radius: 0 },
    "mark-line": { strokeWidth: 1.5 },
    "mark-area": { opacity: 0.85, radius: 0 },
    annotation: { fill: "#111827", font: 9, letterSpacing: 0.2 },
    label: { fill: "#374151", font: 8, letterSpacing: 0.08 },
    chrome: { fill: "#f3f4f6", stroke: "#9ca3af", strokeWidth: 1 },
    hud: { fill: "#111827", font: 10, letterSpacing: 0.12 },
    atmosphere: { opacity: 0 },
  },
  layers: [
    { match: "backdrop*", role: "atmosphere", opacity: 0 },
    { match: "colorWash*", role: "atmosphere", opacity: 0 },
    { match: "typography", props: {} },
  ],
  inference: {
    patterns: [
      { pattern: "^(title|.*Title)$", role: "title" },
      { pattern: "^(subtitle|caption|.*Caption)$", role: "subtitle" },
      { pattern: "^(axis|.*Axis|vecAxis)", role: "axis" },
      { pattern: "(grid|Grid)", role: "grid" },
      { pattern: "^(leg|barLeg|leg)", role: "legend" },
      { pattern: "(Lbl|Label)$", role: "legend-label" },
      { pattern: "^panelLbl", role: "panel-label" },
      { pattern: "SubDeck$", role: "subpanel" },
      { pattern: "Deck$", role: "panel" },
      { pattern: "PlotBg$", role: "plot" },
      { pattern: "^bar$", role: "mark" },
      { pattern: "^seg_", role: "mark-line" },
      { pattern: "^mark$", role: "mark" },
      { pattern: "^linePt$", role: "mark" },
    ],
  },
  policies: {
    allowGlow: false,
    allowBlur: false,
    allowShadow: false,
    allowAtmosphereBlend: false,
    forbidBlendModes: ["screen", "overlay", "soft-light", "multiply"],
    maxMajorTicks: 6,
    plotFloor: 0.22,
    minorTicks: true,
  },
};
